#pragma once

#include "psprecomp/runtime.hpp"

#include <cstddef>
#include <cstdint>

namespace pes6 {

// One code overlay from PSP_GAME/USRDIR/over.afs, recompiled ahead of time.
// The table itself (kOverlays) is generated by scripts/extract_overlays.py
// from the user's ISO, so it lives under generated/ and is never published.
struct OverlayDescriptor {
    const char *name;
    std::uint32_t id;
    std::uint32_t load_address;
    std::uint32_t image_size;   // 64-byte MWo3 header + text + data
    std::uint32_t bss_size;
    std::uint64_t image_hash;   // FNV-1a 64 of the image bytes
    void (*register_functions)(psprecomp::Runtime &);
};

extern const OverlayDescriptor kOverlays[];
extern const std::size_t kOverlayCount;

// Keeps the runtime's registered code in sync with the overlays resident in
// guest memory: code in a region is dropped when the guest reads new bytes
// over it, and the matching translation is registered lazily the first time
// the guest jumps into it.
void install_overlay_manager(psprecomp::Runtime &runtime);

// Must be called after every host write into guest memory that may load an
// overlay (file and disc reads).
void overlay_memory_written(psprecomp::Runtime &runtime, std::uint32_t address, std::uint32_t size);

} // namespace pes6
